"""Diffusion metrics utilities.

This module is designed for diffusion model evaluation where you have:
- A *real* test dataset (reference distribution)
- A *synthetic* dataset generated by a diffusion sampler (generated distribution)
- Per-sample modality metadata (e.g., t1w, t2w, flair, ...)

Metrics:
- FID on deep feature vectors (e.g., MedicalNet ResNet50 features).
- MMD on the same deep feature vectors.
- MS-SSIM *diversity* on synthetic samples *within each modality*:
    We compute MS-SSIM on randomly sampled pairs of synthetic images, grouped by modality.
    Lower MS-SSIM indicates higher diversity.

Notes:
- FID expects (N, D) features.
- MMD requires y_pred and y to have the same shape (we subsample to match).
- Optional intensity normalisation (minmax or zscore) can be applied inside the
  calculator *before* feature extraction.
"""

import math
from collections import defaultdict
from typing import Any, Dict, Iterable, List, Mapping, MutableMapping, Sequence, Tuple

import numpy as np
import torch
from medmetric.metrics import FID, MMD, MS_SSIM
from monai.utils import MetricReduction

try:
    from tqdm.auto import tqdm
except ImportError:  # pragma: no cover - exercised only without optional extra

    def tqdm(iterable, *args, **kwargs):
        return iterable

# from brainmint.data.utils import adaptive_background_mask

class DiffusionMetricCalculator:
    """Feature extraction and normalization logic for diffusion metrics."""

    METRIC_NAMES: Tuple[str, ...] = ("fid", "mmd", "ms_ssim")

    def __init__(
        self,
        feature_extractor: torch.nn.Module,
        modalities: Sequence[str],
        *,
        intensity_normalization: str | None = "zscore-dataset",  # None, "minmax", "zscore", "zscore-dataset".
        modality_stats: Mapping[str, Mapping[str, float]] | None = None,
        mask_quantile: float = 0.10,
        mask_eps: float = 1e-3,
    ) -> None:
        self.feature_extractor = feature_extractor
        self.feature_extractor.eval()

        self.modalities = [str(m).strip().lower() for m in modalities] if modalities else []

        self.intensity_normalization = intensity_normalization
        self._modality_stats = modality_stats
        self._mask_quantile = float(mask_quantile)
        self._mask_eps = float(mask_eps)

    @property
    def metric_names(self) -> Tuple[str, ...]:
        return self.METRIC_NAMES

    def process_batch(
        self,
        syn: torch.Tensor,
        real: torch.Tensor,
        modalities_batch: Sequence[str],
    ) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        """Return (real_feats, syn_feats, syn_images)."""
        if syn.shape != real.shape:
            raise ValueError(f"Real and synthetic must match shapes; got {tuple(real.shape)} vs {tuple(syn.shape)}")
        if syn.ndim < 3:
            raise ValueError("Expected tensors with batch, channel, and spatial dims.")
        if len(modalities_batch) != int(syn.shape[0]):
            raise ValueError(
                f"Expected one modality label per sample; got {len(modalities_batch)} for batch size {int(syn.shape[0])}."
            )

        syn = syn.float()
        real = real.float()
        self._validate_numerics(syn, real)

        # Normalise intensities before feature extraction (FID/MMD).
        syn_eval = self._apply_intensity_normalization(syn, modalities_batch=modalities_batch)
        real_eval = self._apply_intensity_normalization(real, modalities_batch=modalities_batch)

        with torch.no_grad():
            real_feats = self.extract_features(real_eval)
            syn_feats = self.extract_features(syn_eval)

        return real_feats, syn_feats, syn

    def extract_features(self, x: torch.Tensor) -> torch.Tensor:
        feats = self.feature_extractor(x)
        if feats.ndim > 2:
            feats = feats.flatten(1)
        if feats.ndim != 2:
            raise ValueError(f"Feature extractor must return (B,D) after pooling/flatten; got {tuple(feats.shape)}")
        return feats.detach().to(dtype=torch.float32, device="cpu")

    def _apply_intensity_normalization(
        self, x: torch.Tensor, *, modalities_batch: Sequence[str] | None = None
    ) -> torch.Tensor:
        """Apply per-sample intensity normalisation.

        Supports:
          - None: no-op
          - "minmax": (x - min) / (max - min) per sample/channel
          - "zscore": (x - mean) / std per sample/channel
          - "zscore-dataset": (x - mean) / std per modality stats with adaptive mask
        """
        mode = self.intensity_normalization
        if mode is None:
            return x

        mode = str(mode).strip().lower()
        if mode in ("", "none"):
            return x

        spatial_dims = tuple(range(2, x.ndim))
        eps = 1e-6

        if mode in ("minmax", "min-max", "min_max"):
            x_min = x.amin(dim=spatial_dims, keepdim=True)
            x_max = x.amax(dim=spatial_dims, keepdim=True)
            denom = (x_max - x_min).clamp_min(eps)
            return (x - x_min) / denom

        if mode in ("zscore", "z-score", "z_score"):
            mean = x.mean(dim=spatial_dims, keepdim=True)
            std = x.std(dim=spatial_dims, keepdim=True, unbiased=False).clamp_min(eps)
            return (x - mean) / std

        if mode in ("zscore-dataset", "zscore_dataset", "z-score-dataset"):
            if modalities_batch is None:
                raise ValueError("Modality labels are required for zscore-dataset normalization.")
            if self._modality_stats is None:
                raise ValueError("Missing modality_stats for zscore-dataset normalization.")
            if len(modalities_batch) != int(x.shape[0]):
                raise ValueError("Metadata lengths do not match image batch tensors.")

            normalized: List[torch.Tensor] = []
            for idx, modality in enumerate(modalities_batch):
                key = str(modality).strip().lower()
                stats = self._modality_stats.get(key)
                if stats is None:
                    raise KeyError(f"Missing intensity stats for modality '{modality}'.")
                sample = x[idx]
                # The backgroud is not perfect especially for synthetic images.
                # Therefore skipping masking!!!!
                # mask = adaptive_background_mask(sample, quantile=self._mask_quantile, eps=self._mask_eps)
                mean = torch.as_tensor(stats["mean"], device=sample.device, dtype=sample.dtype)
                std = torch.as_tensor(stats["std"], device=sample.device, dtype=sample.dtype)
                std = std.clamp_min(eps)
                normalized_sample = (sample - mean) / std
                # background = torch.zeros((), device=sample.device, dtype=sample.dtype)
                normalized.append(normalized_sample)
            return torch.stack(normalized, dim=0)

        raise ValueError(
            "Unknown intensity_normalization="
            f"'{self.intensity_normalization}'. Allowed: None, 'minmax', 'zscore', 'zscore-dataset'."
        )

    @staticmethod
    def _validate_numerics(preds: torch.Tensor, refs: torch.Tensor) -> None:
        for tensor, name in ((preds, "predictions"), (refs, "targets")):
            if not torch.isfinite(tensor).all():
                raise ValueError(f"{name.capitalize()} contain NaN or Inf values.")


class DiffusionMetricAggregator:
    """Aggregate deep features (FID/MMD) and MS-SSIM diversity per modality and overall."""

    def __init__(
        self,
        modalities: Sequence[str] | None = None,
        *,
        seed: int = 42,
        device: torch.device | str | None = None,
        ms_ssim_data_range: float = 1.0,
        ms_ssim_intensity_normalization: str | None = None,
        ms_ssim_kernel_type: str | None = None,
        ms_ssim_kernel_sigma: float | Sequence[float] | None = None,
        ms_ssim_k1: float | None = None,
        ms_ssim_k2: float | None = None,
        ms_ssim_max_pairs: int = 5000,
        ms_ssim_pair_batch_size: int = 16,
    ) -> None:
        self._rng = np.random.default_rng(int(seed))
        self._device = (
            torch.device(device) if device is not None else torch.device("cuda" if torch.cuda.is_available() else "cpu")
        )

        self._ms_ssim_data_range = float(ms_ssim_data_range)
        self._ms_ssim_intensity_normalization = ms_ssim_intensity_normalization
        self._ms_ssim_kernel_type = ms_ssim_kernel_type
        self._ms_ssim_kernel_sigma = ms_ssim_kernel_sigma
        self._ms_ssim_k1 = ms_ssim_k1
        self._ms_ssim_k2 = ms_ssim_k2
        self._ms_ssim_max_pairs = int(ms_ssim_max_pairs)
        self._ms_ssim_pair_batch_size = int(ms_ssim_pair_batch_size)

        self._real_feats: MutableMapping[str, List[torch.Tensor]] = defaultdict(list)
        self._syn_feats: MutableMapping[str, List[torch.Tensor]] = defaultdict(list)
        self._syn_images: MutableMapping[str, List[torch.Tensor]] = defaultdict(list)

        self._counts: MutableMapping[str, int] = defaultdict(int)
        self._order: List[str] = []
        self._seen_modalities: set[str] = set()

        if modalities is not None:
            for m in modalities:
                key = self._normalise_modality(m)
                if key not in self._order:
                    self._order.append(key)
            self._seen_modalities = set(self._order)

        self._ms_ssim_metric: MS_SSIM | None = None
        self._ms_ssim_dims: int | None = None
        self._ms_ssim_win_size: int | None = None

    @staticmethod
    def _normalise_modality(modality: str) -> str:
        return str(modality).strip().lower() or "unknown"

    @staticmethod
    def _format_modality(modality: str) -> str:
        key = modality.strip().lower()
        if key == "overall":
            return "Overall"
        if not key:
            return "Unknown"
        if len(key) <= 3:
            return key.upper()
        return key.capitalize()

    def add_features_batch(
        self,
        modalities: Sequence[str],
        real_feats: torch.Tensor,
        syn_feats: torch.Tensor,
        syn_images: torch.Tensor,
    ) -> None:
        if len(modalities) != int(real_feats.shape[0]):
            raise ValueError("Metadata lengths do not match feature batch tensors.")
        if real_feats.shape != syn_feats.shape:
            raise ValueError(
                f"Real and synthetic feature shapes must match, got {real_feats.shape} vs {syn_feats.shape}"
            )

        real_feats = real_feats.detach().cpu()
        syn_feats = syn_feats.detach().cpu()
        syn_images = syn_images.detach().cpu()

        for i, mod in enumerate(modalities):
            key = self._normalise_modality(mod)
            if key not in self._seen_modalities:
                self._order.append(key)
                self._seen_modalities.add(key)

            self._real_feats[key].append(real_feats[i : i + 1])
            self._syn_feats[key].append(syn_feats[i : i + 1])
            self._syn_images[key].append(syn_images[i : i + 1])
            self._counts[key] += 1

    @staticmethod
    def _mean(values: Iterable[float]) -> float:
        vals = list(values)
        if not vals:
            return float("nan")
        finite = [v for v in vals if math.isfinite(v)]
        if not finite:
            return float("nan")
        return float(np.mean(finite))

    def _stack_feats(self, feats: List[torch.Tensor]) -> torch.Tensor:
        if not feats:
            return torch.empty((0, 0), dtype=torch.float32)
        x = torch.cat(feats, dim=0)
        # if x.ndim > 2:
        #     x = x.flatten(1)
        if x.ndim != 2:
            raise ValueError(f"Expected stacked features to be (N,D), got {tuple(x.shape)}")
        return x

    @staticmethod
    def _stack_images(images: List[torch.Tensor]) -> torch.Tensor:
        if not images:
            raise ValueError("No synthetic images collected; cannot compute MS-SSIM.")
        x = torch.cat(images, dim=0)
        return x

    def _match_counts_for_mmd(self, real: torch.Tensor, syn: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        n_r = int(real.shape[0])
        n_s = int(syn.shape[0])
        if n_r == n_s:
            return real, syn
        n = min(n_r, n_s)
        if n < 2:
            return real[:n], syn[:n]

        if n_r > n:
            idx = self._rng.choice(n_r, size=n, replace=False)
            real = real[idx]
        if n_s > n:
            idx = self._rng.choice(n_s, size=n, replace=False)
            syn = syn[idx]
        return real, syn

    @staticmethod
    def sample_random_pairs(n: int, k: int, rng: np.random.Generator) -> tuple[torch.Tensor, torch.Tensor]:
        """Sample k unique unordered pairs (i, j) with i < j uniformly."""
        if n < 2 or k <= 0:
            return torch.empty((0,), dtype=torch.long), torch.empty((0,), dtype=torch.long)

        num_pairs = n * (n - 1) // 2
        k = min(k, num_pairs)

        if k == num_pairs:
            pair_indices = np.arange(num_pairs)
        else:
            pair_indices = rng.choice(num_pairs, size=k, replace=False)

        counts = np.arange(n - 1, 0, -1)
        cum_counts = np.cumsum(counts)
        i = np.searchsorted(cum_counts, pair_indices, side="right")
        prev = np.concatenate(([0], cum_counts[:-1]))
        offset = pair_indices - prev[i]
        j = i + 1 + offset

        return torch.from_numpy(i).long(), torch.from_numpy(j).long()

    def _ensure_ms_ssim_metric(self, spatial_dims: int, spatial_shape: Sequence[int]) -> None:
        win_size = self._determine_ms_ssim_window(spatial_shape)
        if self._ms_ssim_metric is None or self._ms_ssim_dims != spatial_dims or self._ms_ssim_win_size != win_size:
            ms_kwargs = dict(
                spatial_dims=spatial_dims,
                data_range=self._ms_ssim_data_range,
                kernel_size=win_size,
                reduction=MetricReduction.NONE,
            )
            if self._ms_ssim_kernel_type is not None:
                ms_kwargs["kernel_type"] = self._ms_ssim_kernel_type
            if self._ms_ssim_kernel_sigma is not None:
                ms_kwargs["kernel_sigma"] = self._ms_ssim_kernel_sigma
            if self._ms_ssim_k1 is not None:
                ms_kwargs["k1"] = self._ms_ssim_k1
            if self._ms_ssim_k2 is not None:
                ms_kwargs["k2"] = self._ms_ssim_k2

            self._ms_ssim_metric = MS_SSIM(**ms_kwargs)
            self._ms_ssim_dims = spatial_dims
            self._ms_ssim_win_size = win_size

    @staticmethod
    def _determine_ms_ssim_window(spatial_shape: Sequence[int]) -> int:
        if not spatial_shape:
            raise ValueError("Spatial dimensions required to configure MS-SSIM metric.")

        min_dim = min(int(dim) for dim in spatial_shape)
        num_scales = 5
        weights_div = max(1, (num_scales - 1)) ** 2
        max_kernel_from_ms = max(1, min_dim // weights_div)

        max_kernel = min(11, max_kernel_from_ms)
        if max_kernel % 2 == 0:
            max_kernel = max(1, max_kernel - 1)

        if max_kernel < 3:
            raise ValueError(
                f"MS-SSIM cannot be computed for spatial size {spatial_shape}: "
                f"minimum dimension {min_dim} is too small for default 5-scale MS-SSIM."
            )
        return max_kernel

    def _apply_ms_ssim_intensity_normalization(self, x: torch.Tensor) -> torch.Tensor:
        mode = self._ms_ssim_intensity_normalization
        if mode is None:
            return x

        mode = str(mode).strip().lower()
        if mode in ("", "none"):
            return x

        spatial_dims = tuple(range(2, x.ndim))
        eps = 1e-6

        if mode in ("minmax", "min-max", "min_max"):
            x_min = x.amin(dim=spatial_dims, keepdim=True)
            x_max = x.amax(dim=spatial_dims, keepdim=True)
            denom = (x_max - x_min).clamp_min(eps)
            return (x - x_min) / denom

        if mode in ("zscore", "z-score", "z_score"):
            mean = x.mean(dim=spatial_dims, keepdim=True)
            std = x.std(dim=spatial_dims, keepdim=True, unbiased=False).clamp_min(eps)
            return (x - mean) / std

        raise ValueError(
            f"Unknown ms_ssim_intensity_normalization='{self._ms_ssim_intensity_normalization}'. "
            "Allowed: None, 'minmax', 'zscore'."
        )

    @staticmethod
    def _finalise_metric_values(values: torch.Tensor, batch_size: int) -> torch.Tensor:
        values = values.detach().cpu()
        if values.shape[0] != batch_size:
            raise ValueError(
                f"Metric output batch dimension does not match inputs; expected {batch_size}, got {values.shape[0]}."
            )
        if values.ndim == 2 and values.shape[1] == 1:
            values = values.squeeze(dim=1)
        elif values.ndim > 1 and any(dim != 1 for dim in values.shape[1:]):
            raise ValueError(
                f"Expected MS-SSIM metric to return per-sample scalars; received shape {tuple(values.shape)}."
            )
        return values

    def _compute_ms_ssim_mean(self, syn_images: torch.Tensor) -> float:
        if syn_images.numel() == 0 or syn_images.shape[0] == 0:
            return float("nan")
        if syn_images.ndim < 3:
            raise ValueError("Expected synthetic tensors with batch, channel, and spatial dims.")

        n = int(syn_images.shape[0])
        if n < 2:
            return float("nan")

        spatial_dims = syn_images.ndim - 2
        if spatial_dims != 3:
            raise ValueError(f"Expected 3D volumes (spatial_dims=3), got {spatial_dims}")

        num_pairs = n * (n - 1) // 2
        max_pairs = max(0, self._ms_ssim_max_pairs)
        k = int(min(max_pairs, num_pairs))
        if k == 0:
            return float("nan")

        self._ensure_ms_ssim_metric(spatial_dims, syn_images.shape[2:])

        i_idx, j_idx = self.sample_random_pairs(n, k, rng=self._rng)

        total = 0.0
        count = 0
        batch_size = max(1, self._ms_ssim_pair_batch_size)

        device = self._device
        steps = math.ceil(k / batch_size)
        with torch.no_grad():
            for step in tqdm(range(steps), desc="MS-SSIM pairs", leave=False):
                start = step * batch_size
                end = min(k, start + batch_size)
                idx_a = i_idx[start:end]
                idx_b = j_idx[start:end]
                a = syn_images[idx_a].to(device, non_blocking=True)
                b = syn_images[idx_b].to(device, non_blocking=True)
                a = self._apply_ms_ssim_intensity_normalization(a)
                b = self._apply_ms_ssim_intensity_normalization(b)

                assert self._ms_ssim_metric is not None
                vals = self._ms_ssim_metric(y_pred=a, y=b)
                vals = self._finalise_metric_values(vals, int(end - start))

                total += float(vals.sum().item())
                count += int(vals.numel())

        return float(total / max(count, 1))

    @staticmethod
    def _compute_fid(real: torch.Tensor, syn: torch.Tensor) -> float:
        """Compute FID using a fresh metric instance to avoid state leakage."""
        fid_metric = FID()
        return float(fid_metric(fake_feats=syn, real_feats=real).item())

    @staticmethod
    def _compute_mmd(real: torch.Tensor, syn: torch.Tensor) -> float:
        """Compute MMD using a fresh metric instance to avoid state leakage."""
        mmd_metric = MMD()
        return float(mmd_metric(fake_feats=syn, real_feats=real).item())

    def summary_rows(self) -> List[Dict[str, Any]]:
        rows: List[Dict[str, Any]] = []

        seen: set[str] = set()
        for key in self._order:
            if key in seen:
                raise KeyError(f"Key:{key} has already been seen and processed.")
            seen.add(key)

            count = int(self._counts.get(key, 0))
            real = self._stack_feats(self._real_feats.get(key))
            syn = self._stack_feats(self._syn_feats.get(key))
            syn_images = self._stack_images(self._syn_images.get(key))
            ms_mean = self._compute_ms_ssim_mean(syn_images)

            fid_val = float("nan")
            mmd_val = float("nan")

            if real.shape[0] >= 2 and syn.shape[0] >= 2 and real.shape[1] == syn.shape[1]:
                try:
                    fid_val = self._compute_fid(real=real, syn=syn)
                except Exception:
                    fid_val = float("nan")

                try:
                    r_m, s_m = self._match_counts_for_mmd(real, syn)
                    if r_m.shape[0] >= 2 and s_m.shape[0] >= 2 and r_m.shape == s_m.shape:
                        mmd_val = self._compute_mmd(real=r_m, syn=s_m)
                except Exception:
                    mmd_val = float("nan")

            rows.append(
                {
                    "modality": self._format_modality(key),
                    "count": count,
                    "fid": fid_val,
                    "mmd": mmd_val,
                    "ms_ssim": ms_mean,
                }
            )
        overall = self._compute_weighted_overall(rows)
        if overall is not None:
            rows.append(overall)
        return rows

    def _compute_weighted_overall(self, rows: Sequence[Mapping[str, Any]]) -> Dict[str, Any] | None:
        """Compute count-weighted overall metrics from per-modality rows (no pooled features)."""
        weights = [int(r.get("count", 0)) for r in rows]
        total = sum(weights)
        if total <= 0:
            return None

        def weighted_average(key: str) -> float:
            values = [r.get(key) for r in rows]
            weighted = [w * float(v) for w, v in zip(weights, values)]
            return float(sum(weighted) / total)

        # Overall values are count-weighted averages across modalities, not pooled features.
        return {
            "modality": self._format_modality("overall"),
            "count": total,
            "fid": weighted_average("fid"),
            "mmd": weighted_average("mmd"),
            "ms_ssim": weighted_average("ms_ssim"),
        }
